# Generated by Django 2.0 on 2020-02-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={},
        ),
    ]
