# Generated by Django 2.0 on 2020-02-25 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(upload_to='%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'gif'], message='文件必须是图片')]),
        ),
    ]
