# Generated by Django 2.0 on 2020-02-20 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20200220_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_articles', related_query_name='u_a', to='front.FrontUser'),
        ),
    ]
