# Generated by Django 2.0 on 2020-02-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-pub_time'],
            },
        ),
    ]
