"""empty message

Revision ID: 29052de35993
Revises: e90d05ed4ca1
Create Date: 2020-02-12 11:41:11.087100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29052de35993'
down_revision = 'e90d05ed4ca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('posts_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collections')
    # ### end Alembic commands ###
