# Generated by Django 2.0 on 2020-02-19 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='title', max_length=100, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-create_time'],
            },
        ),
    ]
